class TestCallbackObject < ActiveRecord::Base
  def local_condition1: () -> bool
  def local_condition2: () -> bool
  def local_condition3: () -> bool

  RAILS_72_DOCS_EXAMPLE: [Symbol, ^(TestCallbackObject) [self: TestCallbackObject] -> bool, Proc]

  def custom_validation: () -> void
end

module Callbacks
  class ClassCallback
    def self.before_validation: (untyped) -> void

    def self.after_validation: (untyped) -> void

    def self.before_save: (untyped) -> void

    def self.before_create: (untyped) -> void

    def self.after_create: (untyped) -> void

    def self.after_save: (untyped) -> void

    def self.around_create: (untyped) { () -> void } -> void

    def self.around_save: (untyped) { () -> void } -> void
  end
end

class TestRelationDelegation < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestRelationDelegation, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestRelationDelegation, ActiveRecord_Relation, Integer]

  def self.delegated_on_a_relation: () -> void
end

class TestModelBuild < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestModelBuild, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestModelBuild, ActiveRecord_Relation, Integer]

  def self.builds: () -> void
  def own_method: () -> void
end
