class TestCallbackObject < ActiveRecord::Base
end

module Callbacks
  class ClassCallback
    def self.before_validation: (untyped) -> void

    def self.after_validation: (untyped) -> void

    def self.before_save: (untyped) -> void

    def self.before_create: (untyped) -> void

    def self.after_create: (untyped) -> void

    def self.after_save: (untyped) -> void

    def self.around_create: (untyped) { () -> void } -> void

    def self.around_save: (untyped) { () -> void } -> void
  end
end

class TestRelationDelegation < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestRelationDelegation, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestRelationDelegation, ActiveRecord_Relation, Integer]

  def self.delegated_on_a_relation: () -> void
end

class TestModelBuild < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestModelBuild, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestModelBuild, ActiveRecord_Relation, Integer]

  def self.builds: () -> void
  def own_method: () -> void
end

class TestInBatches < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestInBatches, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestInBatches, ActiveRecord_Relation, Integer]

  def self.batches: () -> void
  def own_method: () -> void
end

class TestGroupedRelation < ActiveRecord::Base
  class ActiveRecord_Relation < ActiveRecord::Relation
    include ActiveRecord::Relation::Methods[TestGroupedRelation, Integer]
  end

  extend ActiveRecord::Base::ClassMethods[TestGroupedRelation, ActiveRecord_Relation, Integer]

  def self.grouped: () -> void
  def own_method: () -> void
end
